### ISSUE TITLE
Docker meet Firewall comments

### ISSUE THREAD

**Issue by dmaestro** [Jc2k/Jc2k.github.io#1]
2017-08-15-docker-firewall.md

Wow! What a great post! I'm new to Docker, so I wondered why a docker install broke my ethernet bridge on my Debian Jesse server. This explained it all and helped me solve it.

I would suggest a couple of edits for clarity:

* You say "Don’t change the FORWARD chain to ACCEPT from DROP. There is no need any more." 
  and I agree. But in `/etc/iptables.conf`, you begin with this:
  ```
  *filter
  :INPUT ACCEPT [0:0]
  :FORWARD ACCEPT [0:0]  # <== This should be DROP, no?
  :OUTPUT ACCEPT [0:0]
  :FILTERS - [0:0]
  :DOCKER-USER - [0:0]
  ```
* This may be distribution / OS dependent, but I don't find any `--now` option for this command:
  ```
  And enable it:
  $ sudo systemctl enable --now iptables
  ```
  The systemd man page (what I find) says to run `start` as a separate command:
  ```
  $ sudo systemctl enable iptables
  $ sudo systemctl start iptables    # start it now
  ```
* I'm familiar with iptables, but maybe not an expert ;-) - I don't understand why the `1.2.3.4` rule
  has no target? My understanding is that the rule would be ignored (but my understanding of the
  masquerading and extension stuff is limited ...)
  ```
  -A FILTERS -m state --state ESTABLISHED,RELATED -j ACCEPT
  -A FILTERS -m state --state NEW -s 1.2.3.4/32
  -A FILTERS -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
  ```

Thanks again for a great post :-)

**Comment by Jc2k** [comment]
Thank you for the feedback! And double thanks for being so polite about my silly mistakes, its a rare treat these days.

Hopefully I've fixed the errors in the examples now. I guess `--now` is newer than Jessie and older than Xenial. I think it's in Stretch. I have got both ways of doing it now.

Thanks again!
